export const data = {
  action: '#',
  method: 'post',
  class: 'registration__form',
  header: {
    class: 'registration__header',
    title: 'Регистрация',
  },
  inputs: [
    {
      id: 'first_name',
      title: 'Фамилия',
      type: 'text',
      name: 'first_name',
      placeholder: 'Фамилия',
    },
    {
      id: 'login',
      title: 'Логин',
      type: 'text',
      name: 'login',
      placeholder: 'Ваш логин',
      icon: 'user',
    },
    {
      id: 'second_name',
      title: 'Имя',
      type: 'text',
      name: 'first_name',
      placeholder: 'Имя',
    },
    {
      id: 'password',
      title: 'Пароль',
      type: 'password',
      name: 'password',
      placeholder: 'Пароль',
      icon: 'hide',
    },
    {
      id: 'email',
      title: 'Почта',
      type: 'email',
      name: 'email',
      placeholder: 'Имя',
      value: 'pochta@yandex.ru',
      icon: 'phone',
    },
    {
      id: 'password-repeated',
      title: 'Пароль (еще раз)',
      type: 'password',
      name: 'password-repeated',
      placeholder: 'Пароль (еще раз)',
    },
    {
      id: 'phone',
      title: 'Телефон',
      type: 'tel',
      name: 'phone',
      placeholder: '+7 (924) 896 33 79',
      value: '+7 (924) 896 33 79',
    },
  ],
  button: {
    class: 'btn--blue',
    text: 'Зарегистрироваться',
    type: 'submit',
  },
  link: {
    url: 'login',
    text: 'Войти',
    class: 'registration__link',
  },
};
